spring:
  application:
    name: SCW-PROJECT
  datasource:
    username: root
    password: duyongheng
    url: jdbc:mysql://127.0.0.1:3306/zcw?serverTimezone=Hongkong&useSSL=false&useUnicode=true&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver


  redis:
    host: 127.0.0.1
    port: 6379
    password: duyongheng
#
#mybatis:
#   config-location: classpath:/mybatis/mybatis-config.xml
#   mapper-locations: classpath:/mybatis/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-PROJECT
    prefer-ip-address: true
    
server:
  port: 8091
  
logging:
  level:
    root: WARN
    org:
      springframework:
      boot:
            autoconfigure:error

