spring:
  application:
    name: SCW-USER
  datasource:
    username: root
      password: duyongheng
      url: jdbc:mysql://127.0.0.1:3306/zcw?serverTimezone=Hongkong&useSSL=false&useUnicode=true&characterEncoding=UTF-8
      driver-class-name: com.mysql.cj.jdbc.Driver
#  redis:
#    host: 192.168.137.3
#    port: 6379
#    #password: 123456
#
#mybatis:
#   config-location: classpath:/mybatis/mybatis-config.xml
#   mapper-locations: classpath:/mybatis/mapper/*.xml

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    appname: SCW-USER
    prefer-ip-address: true
    
server:
  port: 8083
  
logging:
  level:
    root: WARN
    org:
      springframework:
      boot:
            autoconfigure:error

